const PRIMARY = "#1ED760"
const PRIMARY_LIGHT = "#19E68C"
const PRIMARY_DARK = "#117A37"

const SECONDARY = "#2941AB"
const SECONDARY_LIGHT = "#1D75DE"
const SECONDARY_DARK = "#273B94"

const SUCCESS = "#1db954"
const FAILURE = "#e22134"
const WARNING = "#ff5722"

const GREY = "#121212"
const BLACK = "#000000"
const WHITE = "#FFFFFF"

const Colours = {
	PRIMARY,
	PRIMARY_LIGHT,
	PRIMARY_DARK,
	SECONDARY,
	SECONDARY_LIGHT,
	SECONDARY_DARK,
	SUCCESS,
	FAILURE,
	WARNING,
	GREY,
	BLACK,
	WHITE
}

export default Colours